global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']